x-veld:
  chain:

services:
  veld_step_8_analyse_semantic_drift:
    build: ./code/analyse_semantic_drift/
    command: jupyter lab --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    volumes:
      - ./code/analyse_semantic_drift/:/veld/code/
      - ./code/analyse_semantic_drift/jupyter_config/:/veld/storage/jupyter_config/
      - ./data/step_7_word2vec_models__vs300_w6_mc10/:/veld/input/models/
      - ./data/step_6_clean/clean/:/veld/input/texts/
      - ./data/step_8_analysis_cache/:/veld/storage/cache/

