x-veld:
  chain:

services:
  veld_step_2_preprocess:
    build: ./code/preprocess/
    command: python /veld/code/preprocess.py
    volumes:
      - ./code/preprocess/src/:/veld/code/
      - ./data/step_1_raw_data/dta-lingattr-tei_2020-07-27/:/veld/input/
      - ./data/step_2_preprocessed_data/:/veld/output/

